version: "3"
services:
  db-cryptodiff:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cryptodiff
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: root

=======
      MYSQL_ROOT_PASSWORD: root
>>>>>>> integration
