spring:
  datasource:
    url: jdbc:mysql://root:iA0TpA9rV1ASuceRFNe4@containers-us-west-5.railway.app:7855/railway
    username: root
    password: iA0TpA9rV1ASuceRFNe4
  mvc:
    cors:
      allowed-origins: https://cryptodiff-frontend-production.up.railway.app
      allowed-methods: GET, POST, PUT, DELETE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    #database-platform: org.hibernate.dialect.MySQLDialect


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days